### ISSUE TITLE
Trailing periods are incorrectly included in link

### ISSUE THREAD

**Issue by stevemcleod** [barbarysoftware/Linkifier#1]
**Repro**

Run this:

```
   public static void main(String[] args) {
        System.out.println(Linkify.linkify("Visit example.com."));
    }
```

Expected output: 
`Visit <a href='http://example.com.' target='_blank'>example.com</a>.`

Actual output:
`Visit <a href='http://example.com.' target='_blank'>example.com.</a>`

**Comment by akballal** [comment]
I would like to work on this, can you please assign this to me ?

**Comment by dimitriosgialas** [comment]
This one is now fixed and checked in.
